# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9726c29e457d0306e2fdb6bf76464dbacec943e14c30b6db9393d0f14f9daf4fe7680b13259fb6ed5796126066e4fd892901de587ba6823d63876b4913b05589

test:
  secret_key_base: d7144f634dfa71545d5ad0f951f651b858874ac7fd3f1fc4346300e973413ec41dbb1602146f8fbe2b050c01539381e5b22480f64fdf88943fc4e406007f038f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
